/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PostRouteImport } from './routes/post'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as UserUsernameRouteImport } from './routes/user.$username'
import { Route as SettingsSavedRouteImport } from './routes/settings.saved'
import { Route as SettingsReactionsRouteImport } from './routes/settings.reactions'
import { Route as SettingsLikesRouteImport } from './routes/settings.likes'
import { Route as SettingsCommentsRouteImport } from './routes/settings.comments'
import { Route as SettingsArchiveRouteImport } from './routes/settings.archive'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as DreamIdRouteImport } from './routes/dream.$id'
import { Route as ChatRequestsRouteImport } from './routes/chat/requests'
import { Route as ChatConversationIdRouteImport } from './routes/chat/$conversationId'
import { Route as SettingsArchiveIndexRouteImport } from './routes/settings.archive.index'
import { Route as SettingsArchiveDreamsRouteImport } from './routes/settings.archive.dreams'
import { Route as SettingsArchiveDraftsRouteImport } from './routes/settings.archive.drafts'
import { Route as ChatNewUserIdRouteImport } from './routes/chat/new.$userId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUsernameRoute = UserUsernameRouteImport.update({
  id: '/user/$username',
  path: '/user/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSavedRoute = SettingsSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsReactionsRoute = SettingsReactionsRouteImport.update({
  id: '/reactions',
  path: '/reactions',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLikesRoute = SettingsLikesRouteImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCommentsRoute = SettingsCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchiveRoute = SettingsArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => SettingsRoute,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DreamIdRoute = DreamIdRouteImport.update({
  id: '/dream/$id',
  path: '/dream/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRequestsRoute = ChatRequestsRouteImport.update({
  id: '/chat/requests',
  path: '/chat/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatConversationIdRoute = ChatConversationIdRouteImport.update({
  id: '/chat/$conversationId',
  path: '/chat/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsArchiveIndexRoute = SettingsArchiveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsArchiveRoute,
} as any)
const SettingsArchiveDreamsRoute = SettingsArchiveDreamsRouteImport.update({
  id: '/dreams',
  path: '/dreams',
  getParentRoute: () => SettingsArchiveRoute,
} as any)
const SettingsArchiveDraftsRoute = SettingsArchiveDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => SettingsArchiveRoute,
} as any)
const ChatNewUserIdRoute = ChatNewUserIdRouteImport.update({
  id: '/chat/new/$userId',
  path: '/chat/new/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/notifications': typeof NotificationsRoute
  '/post': typeof PostRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/chat/requests': typeof ChatRequestsRoute
  '/dream/$id': typeof DreamIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/settings/archive': typeof SettingsArchiveRouteWithChildren
  '/settings/comments': typeof SettingsCommentsRoute
  '/settings/likes': typeof SettingsLikesRoute
  '/settings/reactions': typeof SettingsReactionsRoute
  '/settings/saved': typeof SettingsSavedRoute
  '/user/$username': typeof UserUsernameRoute
  '/chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/chat/new/$userId': typeof ChatNewUserIdRoute
  '/settings/archive/drafts': typeof SettingsArchiveDraftsRoute
  '/settings/archive/dreams': typeof SettingsArchiveDreamsRoute
  '/settings/archive/': typeof SettingsArchiveIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/notifications': typeof NotificationsRoute
  '/post': typeof PostRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/chat/requests': typeof ChatRequestsRoute
  '/dream/$id': typeof DreamIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/settings/comments': typeof SettingsCommentsRoute
  '/settings/likes': typeof SettingsLikesRoute
  '/settings/reactions': typeof SettingsReactionsRoute
  '/settings/saved': typeof SettingsSavedRoute
  '/user/$username': typeof UserUsernameRoute
  '/chat': typeof ChatIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/chat/new/$userId': typeof ChatNewUserIdRoute
  '/settings/archive/drafts': typeof SettingsArchiveDraftsRoute
  '/settings/archive/dreams': typeof SettingsArchiveDreamsRoute
  '/settings/archive': typeof SettingsArchiveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/notifications': typeof NotificationsRoute
  '/post': typeof PostRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/chat/requests': typeof ChatRequestsRoute
  '/dream/$id': typeof DreamIdRoute
  '/profile/$id': typeof ProfileIdRoute
  '/settings/archive': typeof SettingsArchiveRouteWithChildren
  '/settings/comments': typeof SettingsCommentsRoute
  '/settings/likes': typeof SettingsLikesRoute
  '/settings/reactions': typeof SettingsReactionsRoute
  '/settings/saved': typeof SettingsSavedRoute
  '/user/$username': typeof UserUsernameRoute
  '/chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/chat/new/$userId': typeof ChatNewUserIdRoute
  '/settings/archive/drafts': typeof SettingsArchiveDraftsRoute
  '/settings/archive/dreams': typeof SettingsArchiveDreamsRoute
  '/settings/archive/': typeof SettingsArchiveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/dashboard'
    | '/explore'
    | '/notifications'
    | '/post'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/chat/$conversationId'
    | '/chat/requests'
    | '/dream/$id'
    | '/profile/$id'
    | '/settings/archive'
    | '/settings/comments'
    | '/settings/likes'
    | '/settings/reactions'
    | '/settings/saved'
    | '/user/$username'
    | '/chat/'
    | '/settings/'
    | '/chat/new/$userId'
    | '/settings/archive/drafts'
    | '/settings/archive/dreams'
    | '/settings/archive/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/dashboard'
    | '/explore'
    | '/notifications'
    | '/post'
    | '/reset-password'
    | '/search'
    | '/chat/$conversationId'
    | '/chat/requests'
    | '/dream/$id'
    | '/profile/$id'
    | '/settings/comments'
    | '/settings/likes'
    | '/settings/reactions'
    | '/settings/saved'
    | '/user/$username'
    | '/chat'
    | '/settings'
    | '/chat/new/$userId'
    | '/settings/archive/drafts'
    | '/settings/archive/dreams'
    | '/settings/archive'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/dashboard'
    | '/explore'
    | '/notifications'
    | '/post'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/chat/$conversationId'
    | '/chat/requests'
    | '/dream/$id'
    | '/profile/$id'
    | '/settings/archive'
    | '/settings/comments'
    | '/settings/likes'
    | '/settings/reactions'
    | '/settings/saved'
    | '/user/$username'
    | '/chat/'
    | '/settings/'
    | '/chat/new/$userId'
    | '/settings/archive/drafts'
    | '/settings/archive/dreams'
    | '/settings/archive/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  NotificationsRoute: typeof NotificationsRoute
  PostRoute: typeof PostRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ChatConversationIdRoute: typeof ChatConversationIdRoute
  ChatRequestsRoute: typeof ChatRequestsRoute
  DreamIdRoute: typeof DreamIdRoute
  ProfileIdRoute: typeof ProfileIdRoute
  UserUsernameRoute: typeof UserUsernameRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ChatNewUserIdRoute: typeof ChatNewUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$username': {
      id: '/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof UserUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/saved': {
      id: '/settings/saved'
      path: '/saved'
      fullPath: '/settings/saved'
      preLoaderRoute: typeof SettingsSavedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/reactions': {
      id: '/settings/reactions'
      path: '/reactions'
      fullPath: '/settings/reactions'
      preLoaderRoute: typeof SettingsReactionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/likes': {
      id: '/settings/likes'
      path: '/likes'
      fullPath: '/settings/likes'
      preLoaderRoute: typeof SettingsLikesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/comments': {
      id: '/settings/comments'
      path: '/comments'
      fullPath: '/settings/comments'
      preLoaderRoute: typeof SettingsCommentsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archive': {
      id: '/settings/archive'
      path: '/archive'
      fullPath: '/settings/archive'
      preLoaderRoute: typeof SettingsArchiveRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dream/$id': {
      id: '/dream/$id'
      path: '/dream/$id'
      fullPath: '/dream/$id'
      preLoaderRoute: typeof DreamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/requests': {
      id: '/chat/requests'
      path: '/chat/requests'
      fullPath: '/chat/requests'
      preLoaderRoute: typeof ChatRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$conversationId': {
      id: '/chat/$conversationId'
      path: '/chat/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof ChatConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/archive/': {
      id: '/settings/archive/'
      path: '/'
      fullPath: '/settings/archive/'
      preLoaderRoute: typeof SettingsArchiveIndexRouteImport
      parentRoute: typeof SettingsArchiveRoute
    }
    '/settings/archive/dreams': {
      id: '/settings/archive/dreams'
      path: '/dreams'
      fullPath: '/settings/archive/dreams'
      preLoaderRoute: typeof SettingsArchiveDreamsRouteImport
      parentRoute: typeof SettingsArchiveRoute
    }
    '/settings/archive/drafts': {
      id: '/settings/archive/drafts'
      path: '/drafts'
      fullPath: '/settings/archive/drafts'
      preLoaderRoute: typeof SettingsArchiveDraftsRouteImport
      parentRoute: typeof SettingsArchiveRoute
    }
    '/chat/new/$userId': {
      id: '/chat/new/$userId'
      path: '/chat/new/$userId'
      fullPath: '/chat/new/$userId'
      preLoaderRoute: typeof ChatNewUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsArchiveRouteChildren {
  SettingsArchiveDraftsRoute: typeof SettingsArchiveDraftsRoute
  SettingsArchiveDreamsRoute: typeof SettingsArchiveDreamsRoute
  SettingsArchiveIndexRoute: typeof SettingsArchiveIndexRoute
}

const SettingsArchiveRouteChildren: SettingsArchiveRouteChildren = {
  SettingsArchiveDraftsRoute: SettingsArchiveDraftsRoute,
  SettingsArchiveDreamsRoute: SettingsArchiveDreamsRoute,
  SettingsArchiveIndexRoute: SettingsArchiveIndexRoute,
}

const SettingsArchiveRouteWithChildren = SettingsArchiveRoute._addFileChildren(
  SettingsArchiveRouteChildren,
)

interface SettingsRouteChildren {
  SettingsArchiveRoute: typeof SettingsArchiveRouteWithChildren
  SettingsCommentsRoute: typeof SettingsCommentsRoute
  SettingsLikesRoute: typeof SettingsLikesRoute
  SettingsReactionsRoute: typeof SettingsReactionsRoute
  SettingsSavedRoute: typeof SettingsSavedRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsArchiveRoute: SettingsArchiveRouteWithChildren,
  SettingsCommentsRoute: SettingsCommentsRoute,
  SettingsLikesRoute: SettingsLikesRoute,
  SettingsReactionsRoute: SettingsReactionsRoute,
  SettingsSavedRoute: SettingsSavedRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  NotificationsRoute: NotificationsRoute,
  PostRoute: PostRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ChatConversationIdRoute: ChatConversationIdRoute,
  ChatRequestsRoute: ChatRequestsRoute,
  DreamIdRoute: DreamIdRoute,
  ProfileIdRoute: ProfileIdRoute,
  UserUsernameRoute: UserUsernameRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatNewUserIdRoute: ChatNewUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
